### PR TITLE
Add support for PHP 8

### PR DESCRIPTION
**Pull request by binotaliu**
All tests passed, we are good to go 😎﻿

### CODE REVIEW

**Comment by antonkomarev** [comment]
Cool! Thanks for the contribution. I'm away from the computer till monday, then will merge your request.

**Comment by kslr** [comment]
Looking forward new release :D

**Comment by antonkomarev** [comment]
Sorry, guys, I was too busy these weeks. I was working hard on GitHub Analytics service beta release: https://yhype.me
Will make release new version of Laravel Optimus ASAP.

**Comment by antonkomarev** [comment]
[Laravel Optimus v3.6.0](https://github.com/cybercog/laravel-optimus/releases/tag/3.6.0) has been released with PHP8 support.

**Pull request merged**
