### PR TITLE
Laravel 10.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 9.x.

**Before merging**, you need to:

- Checkout the `l10-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-optimus.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "cybercog/laravel-optimus": "dev-l10-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by robertmarney** [comment]
Please let me know if I can help at all with this upgrade.

**Comment by antonkomarev** [comment]
I'll try to look on it tomorrow

**Comment by antonkomarev** [comment]
We need to wait this PR of the dependency to be merged:
- https://github.com/GrahamCampbell/Laravel-Manager/pull/18

After that we can add Laravel v10 support.

This PR will be closed, new PR
- #35

**Comment by robertmarney** [comment]
Thank you for the update @antonkomarev and your work maintaining the package!

**Comment by antonkomarev** [comment]
@robertmarney [Laravel Optimus v3.9](https://github.com/cybercog/laravel-optimus/releases/tag/3.9.0) has been released with Laravel 10 support.

**Pull request closed without merging**
