### PR TITLE
Add Laravel v10 support

### LINKED ISSUE #34: Update to Laravel 10
Can you update this package to support laravel 10

### PR DESCRIPTION
**Pull request by antonkomarev**
Resolves #34 

This PR will be merged as soon as issues of the dependencies will be resolved:
- https://github.com/GrahamCampbell/Laravel-Manager/issues/19
- https://github.com/GrahamCampbell/Laravel-TestBench/issues/29

### CODE REVIEW

**Comment by ivanvermeyen** [comment]
Hi, seems Graham has updated the test framework for Laravel 10.
If you have the time, can you merge this one?
Thanks a bunch! 👍 👍 👍

**Comment by antonkomarev** [comment]
Will do soon, thanks @ivanvermeyen

**Comment by antonkomarev** [comment]
@ivanvermeyen @joseaneto [Laravel Optimus v3.9](https://github.com/cybercog/laravel-optimus/releases/tag/3.9.0) has been released with Laravel 10 support.

**Comment by ivanvermeyen** [comment]
Great! Thanks! 🚀

**Pull request merged**
